### ISSUE TITLE
Difference between full screen mode and normal mode 

### ISSUE THREAD

**Issue by Dineshraj555** [AY2122S2-CS2103T-T13-1/tp#110]
Observed this while testing the app.

A lot of unused space when app is used in full screen mode.

Normal Mode
<img width="942" alt="Screenshot 2022-03-31 at 12 51 07 PM" src="https://user-images.githubusercontent.com/77185712/160979474-508b44e4-ad29-475e-8752-5b68b0976171.png">

Full Screen mode

<img width="2221" alt="Screenshot 2022-03-31 at 12 53 27 PM" src="https://user-images.githubusercontent.com/77185712/160979570-7a117570-3452-4b33-bc64-5aa4fa69c3a0.png">

**Comment by tsumian** [comment]
Do you think we can set the window to be a certain size (like not resizable) instead?

**Comment by tobihy** [comment]
@tsumian I just realised that you made some edits to the `PetListCard.fxml` file in your ![previous PR](https://github.com/AY2122S2-CS2103T-T13-1/tp/pull/105/commits/4d235aec2a320fd4457c34ba3539e56953c3750f#diff-41f4ed3fd6f5ab3873f7368401e973ad4f6169d4cf0c61ad81e888bd92129dd5), which may have caused this regression. I did not encounter this issue after implementing the GUI initially. Were there any particular reasons why you edited the file that way?

Attached is the fullscreen and windowed behaviour of the GUI from the previous version:

![image](https://user-images.githubusercontent.com/49607782/160983035-842e4085-a4ba-47e3-9bfb-f74f5c1975c0.png)

![image2](https://user-images.githubusercontent.com/49607782/160983285-676910a7-2bec-421a-9e35-46f6dd409f94.png)

**Comment by tsumian** [comment]
I think I modified it through scene builder so I need to check whats the change there. I will take a look and try to fix this

**Comment by Dineshraj555** [comment]
The previous version by @tobihy seems good.

**Comment by tsumian** [comment]
Fixed it to flush all the way when in full screen

![Screenshot 2022-03-31 at 2 50 35 PM](https://user-images.githubusercontent.com/77776878/160994646-50baa651-0621-4680-b201-bafab0f50fa0.png)

However if we try to make the window small with a long appointment, part of the attendance will be truncated. Not sure if this is an issue previously and I may need help fixing this if you think it's a possible bug. If you think its part of the functionality because pet daycare owners may want to view the whole appointment details with location etc. then we can ignore this.

![Screenshot 2022-03-31 at 2 53 05 PM](https://user-images.githubusercontent.com/77776878/160995192-2c962951-d1e8-46ba-8742-a317715bc8b7.png)
